### ISSUE TITLE
Data quality

### ISSUE THREAD

**Issue by MarcNBecker** [MarcNBecker/VVS#105]
1. Do we want to remove Faecher that are not in any Modulplan (FachInstanz)?
2. Do we want to check Faecher for duplicates?
3. Do we want to improve the data quality of Faecher?
4. Do we want to improve the data quality of Module?
5. Do we want to check Dozenten for duplicates?
6. Do we want to remove empty Modulplaene?

**Comment by agp89** [comment]
1. Ask Kunde
2. \+ 5. Yes, if not to much work
3. \+ 4. Wats meant by data quality? 
4.  Ask Kunde

**Comment by MarcNBecker** [comment]
We should ask Holey what we should do with the almost 250 Dozenten who don't have any Kompetenzfach and are not used in any Vorlesung. The rest is done/obsolete.
