### ISSUE TITLE
Datenmigration: Mehrere Terminkonflikte 

### ISSUE THREAD

**Issue by Omnycron** [MarcNBecker/VVS#107]
unter anderem bei WWI12SEA Semester 5 am 26.08.2014.
Sind die Daten einfach so, oder ist irgendwas bei der Migration/ dem Import in meine mysql falsch gelaufen?

**Comment by ddegraf** [comment]
Wie abgesprochen, prüf ich das heute/morgen Abend.

**Comment by MarcNBecker** [comment]
Das sind die Termine. Ich würde da jetzt keine Konfliktauflösung für Altdaten machen..
