### ISSUE TITLE
Dozent angelegt am 2000-01-01

### ISSUE THREAD

**Issue by agp89** [MarcNBecker/VVS#113]
If a new Dozent is created, "angelegt an" is always 2000-01-01

**Comment by Zwanni** [comment]
Should have eben noticed by all testers - good sign for our testing quality
:( :/

agp89 notifications@github.com schrieb am Mi., 8. Apr. 2015 20:57:

**Comment by MarcNBecker** [comment]
No panic. That's a deployment bug. Had to rewrite our sql file because aws has a mysql version that doesn't support multiple "CURRENT_TIMESTAMP" fields. This is intended and won't happen in future deployment, when a correct mysql version is used
