### ISSUE TITLE
Foreign keys

### ISSUE THREAD

**Issue by MarcNBecker** [MarcNBecker/VVS#35]
Check what should happen when deleting something that is used as a foreign key in other tables
Example: Should the deletion of a kurs force the deletion of all vorlesungen

**Comment by agp89** [comment]
Das müssen wir mit dem Kunden absprechen...

**Comment by Zwanni** [comment]
Werde ich mich drum kümmern, könntet ihr mir sagen, was euch sonst noch für
Abhängigkeiten einfallen würden?

agp89 notifications@github.com schrieb am Mi., 4. Mär. 2015 18:21:

**Comment by MarcNBecker** [comment]
Du findest alle bisher implementierten Abhängigkeiten im SQL File fürs vvs.
Da sind alle Fremdschlüsselbeziehungen + Update/Delete Constraints drin

**Comment by MarcNBecker** [comment]
Studiengangsleiter kann nicht gelöscht werden, wenn noch ein User existiert, der diesen Studiengangsleiter repräsentiert
ModulInstanz wird gelöscht, wenn das Modul gelöscht wird
ModulInstanz wird gelöscht, wenn der Modulplan  gelöscht wird.
Modul wird gelöscht, wenn die letzte ModulInstanz gelöscht wird.
FachInstanz wird gelöscht, wenn das Fach gelöscht wird
FachInstanz wird gelöscht, wenn die ModulInstanz gelöscht wird
Fach wird gelöscht, wenn keine FachInstanz und keine Verbindung zu einem Dozent (Kompetenzfach existiert)
Modulplan kann nicht gelöscht werden, wenn ein Kurs den Modulplan verwendet
Studiengangsleiter kann nicht gelöscht werden, wenn ein Kurs für diesen Studiengangsleiter angelegt ist
Blocklagen werden gelöscht, wenn ein Kurs gelöscht wird
Kompetenzfächer werden gelöscht, wenn ein Dozent gelöscht wird
Kompetenzfächer werden gelöscht, wenn das Fach gelöscht wird
Vorlesungen werden gelöscht, wenn ein Kurs gelöscht wird
FachInstanzen dürfen nicht gelöscht werden, ein eine Vorlesung existiert
Termine werden gelöscht, wenn eine Vorlesung gelöscht wird

**Comment by MarcNBecker** [comment]
sollte inzwischen alles passen..
