### ISSUE TITLE
Open date picker on focus

### ISSUE THREAD

**Issue by MarcNBecker** [MarcNBecker/VVS#52]
Open date picker, when the input gets focused. This will also open the date picker when using TAB to go through the input fields. Also in firefox currently a double click is necessary because the first focus on the input doesn't fire an corresponding on-click.

**Comment by MarcNBecker** [comment]
Maybe this can also be solved by moving the on-click/on-focus event from the paper input decorator to the core input element

**Comment by Kathi22** [comment]
Is it a bug of Polymer or our fault?

**Comment by MarcNBecker** [comment]
Should be our fault..because we open the date picker in the on-click event of the input decorator

**Comment by Kathi22** [comment]
Ok, then we should fix it ;)
