### ISSUE TITLE
Improvement ideas for Planung

### ISSUE THREAD

**Issue by MarcNBecker** [MarcNBecker/VVS#62]
- Show conflicts with other apointments (calendar) - implemented!
- Add navigation to the kurs dashboard, when deleting a vorlesung - implemented!
- Add navigation to studiengangsleiter dashboard when specifiying no ID - implemented!
- Enable input of recurring events - implemented!
- Use ranges in the date picker that correspond to the Blocklage - implemented!
- allow only one Klausur - implemented!

**Comment by Kathi22** [comment]
- allow only one Klausur --> implemented

**Comment by Kathi22** [comment]
finished :)
