### ISSUE TITLE
Add BIRT reports

### ISSUE THREAD

**Issue by MarcNBecker** [MarcNBecker/VVS#64]
Finish the export overlay by adding links to the pdf files deployed in birt and the csv export

**Comment by Kathi22** [comment]
csv-export implemented

**Comment by MarcNBecker** [comment]
TODO: Test if groupe csv is importable @ groupE @MrsA-Z @DerGraf92

**Comment by MarcNBecker** [comment]
TODO: Add export overlay to dashboard screens

**Comment by MarcNBecker** [comment]
On vvs/webapp side everything is done to integrate the BIRT reports (Overlay structure, Buttons, URIs and model functions are set up correctly) All you need to do is setup a birt-viewer besides your vvs application and place the reports inside. A zip file with a birt-viewer webapp including the reports will be added to this report as soon as it is available/finished

**Comment by Zwanni** [comment]
Nicolai Csott is currently solving the last issue - tomorrow everything schould be fine.

**Comment by agp89** [comment]
Trying to print the "Vorlesungsplan Hochformat" - already waiting for 10 minutes... Performance issues also expected on productive environment?
![image](https://cloud.githubusercontent.com/assets/6398661/7079917/c6c70982-df2a-11e4-909c-d339e0468c0c.png)

**Comment by MarcNBecker** [comment]
idk..bad performance could also relate to the slow aws instance. I don't how intense the calculations are BIRT does. I think if the server used in production is fast enough, those performance issues should reduce. However BIRT is also not really fast on my own laptop :/
