### ISSUE TITLE
Dropdown Kompetenzfächer Dozenten

### ISSUE THREAD

**Issue by JanDoe91** [MarcNBecker/VVS#66]
Ich muss bei meinem Laptop jedesmal nach unten scrollen, wenn ich ein neues Kompetenzfach anlege. Würde daher vorschlagen die Liste der Kompetenzfächer unterhalb der Dropdown zu platzieren, damit das scrollen zur Dropdown erspart bleibt. Würde dann die Buttons zum Speichern, Löschen und Abbrechen auch auf die gleiche Ebene wie die Dropdown legen
![tmp_dozent](https://cloud.githubusercontent.com/assets/8777655/6777925/652a1988-d14e-11e4-961e-be0f20baa041.JPG)

**Comment by MarcNBecker** [comment]
Ja kann man ändern. Ich würde am Ende eh nochmal vorschlagen eine Art "Usability" Session zu machen und über potentielle UX Verbesserungen zu reden
