### ISSUE TITLE
Feiertagsliste nach Datum sortieren

### ISSUE THREAD

**Issue by JanDoe91** [MarcNBecker/VVS#68]
Wird ein neuer Feiertag erstellt wird er unten in der Liste angehangen. Denke es wäre schöner, wenn die Liste nach einem neuen Eintrag nach dem Datum sortiert wird.

**Comment by MarcNBecker** [comment]
Sortierungen werden aktuell generll niergendso vorgenommen, wenn der User etwas ändert oder hinzufügt. Ist definitiv ein nice to have feature..
