### ISSUE TITLE
Modulplan bei Kurs anlegen zu Pflichtfeld machen

### ISSUE THREAD

**Issue by ddegraf** [MarcNBecker/VVS#75]
Ist kein Modulplan angelegt, führt das Anlegen eines Kurses zu einem Fehlerzustand. Modulplan muss als Pflichtfeld beim Kurs anlegen deklariert werden.

**Comment by MarcNBecker** [comment]
Diesen Bug werden wir nicht fixen. Dropdowns lassen sich nicht leicht als Pflichtfeld kennzeichnen. Ist ein sehr unrealistischer Randfall, dass ein Kurs ohne Modulplaene im System erzeugt werden soll..
