### ISSUE TITLE
IE: User anzeigen/bearbeiten/löschen ungültiger Username

### ISSUE THREAD

**Issue by pschuster1711** [MarcNBecker/VVS#83]
Username ungültig beim anzeigen/bearbeiten/löschen eines Users im Internet Explorer. Dies darf eigentlich nicht sein, da dieser nicht verändert werden darf. (siehe Bild)
![fehler](https://cloud.githubusercontent.com/assets/11459637/6854411/77108a92-d3f1-11e4-8dcf-03e2a4617eaf.jpg)

**Comment by MarcNBecker** [comment]
Tritt das immer auf, oder passiert das nur ab und zu?

**Comment by pschuster1711** [comment]
ich habe das heute das erste Mal gesehen. Ist auch nur im IE und zurzeit tritt das immer auf.
