### ISSUE TITLE
Vorlesungstermin am Feiertag?

### ISSUE THREAD

**Issue by agp89** [MarcNBecker/VVS#87]
Müssen wir das überprüfen? Derzeit kann man einen Vorstellungstermin ohne weiteren Hinweis an einem Feiertag anlegen...

**Comment by MarcNBecker** [comment]
Man kann überlegen, entweder eine Auswahl des Datums an einem Feiertag gar nicht zu erlauben, oder alternativ Konflikte mit Feiertagen darzustellen
