### ISSUE TITLE
Update view after changing a Dozent

### ISSUE THREAD

**Issue by agp89** [MarcNBecker/VVS#88]
das Dropdown der Dozenten auf der Stammdatenübersicht wird nach einer Änderung nicht wie beim Neuanlegen eines Dozenten aktualisiert.

**Comment by MarcNBecker** [comment]
Das ist kein Chrome Problem, sonder liegt einfach daran, da wir wohl die Stammdatenübersicht bei einer Änderung eines Dozenten nicht invalidieren. Es wäre zu prüfen, wie sich die Stammdatenübersicht bei Änderung eines Kursnamens verhält.
