### ISSUE TITLE
Change name of Modulplan?

### ISSUE THREAD

**Issue by agp89** [MarcNBecker/VVS#89]
Man kann den Namen eines Modulplans nicht mehr ändern. Bei den Vorlagen ist das ok aber bei selbst erstellten sollte das änderbar sein oder?

**Comment by MarcNBecker** [comment]
Das war nie geplant und ist deshalb kein Bug. Sollte man sich bei einem Modulplan vertippen muss man ihn löschen und neu anlegen.
